### PR TITLE
refactor: remove `getWeb3`

### LINKED ISSUE #1799: Signing a message from a DApp crashes the app
## Bug description

When triggering a message signing from within a DApp (e.g. Snapshot), the app crashes, throwing the following error:

image

## Environment
 - DApp: Monerium, Snapshot (probably any dapp that requests a signature)
 - Chain: Ethereum/Gnosis Chain

## Steps to reproduce
 1. Open Snapshot.org
 2. Connect a Safe via WalletConnect
 3. Edit Profile on Snapshot
 4. Safe crashes 

## Expected result

The signing modal opens and you are able to sign a message.

## Obtained result

The app crashes.

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1799

## How this PR fixes it

- `getWeb3` has been removed and the `provider` is now drilled accordingly.
- Contract instances have been checked and altered to their read-only counterpart accordingly.

## How to test it

- (Relayed) Safe creation (incl. gas estimation) should work, setting the Fallback Handler correctly.
- Creating/executing/relaying (batched) transaction(s) should work:
  - Simulation should work.
  - Validity of transaction(s) should pass (no warning shown that the transaction may fail).
- Safe updates should work.
- Spending limits should work:
  - Loading of spending limit balancess should work.
  - Removal of spending limits should work.
- Signing on-chain messages via Safe Apps should work.

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by francovenica** [comment]
I have issues with goerli. I don't know if this ticket deals with networks or not but I want to point it out still

With the stg CGW I cannot create safes in goerli
With the stg or prod CGW I cannot execute tx with the tx builder app in goerli

once the sponsored tx run out and I have to use my own funds, I can create the safe and execute the tx with the tx builder just fine.

I didn't have this issues with the GNO chain (I could only test with the prod CGW tho)

**Comment by francovenica** [comment]
Besides the previous comment I was able to use the relayer in the GNO chain pretty well.

The only thing notisable was when I tried to upgrade the safe. I had the warning that the tx could fail, but that error might be that old issue about the GNO chain underestimating how much gas and gas fee it needs to execute these types of tx. I executed the tx anyways with the relayer and it worked fine
image

**Comment by iamacook** [comment]
> With the stg CGW I cannot create safes in goerli With the stg or prod CGW I cannot execute tx with the tx builder app in goerli

Our 1Balance pool was empty and transactions could not be relayed. If you encounter transactions not relaying, be sure to check the network tab for [Gelato requests](https://relay.gelato.digital/tasks/status/0xfd85ff42615944b4886b3397f71a3ea9b58751b3d54a76831957f190aaa5c762).

We have since topped up the pool and transactions are succeeding. I have managed to create Safes/execute transactions successfully.

> The only thing notisable was when I tried to upgrade the safe. I had the warning that the tx could fail, but that error might be that old issue about the GNO chain underestimating how much gas and gas fee it needs to execute these types of tx. I executed the tx anyways with the relayer and it worked fine

There was an issue with the Gnosis Chain RPC yesterday which may have played a role. If the relay succeeded, it leads me to believe that Gelato are likely using a different RPC to us.

I checked this myself and was not shown a warning:

image

Could you try the above again today and let me know if you continue to experience issues?

**Comment by francovenica** [comment]
I've checked Goerli again and now it works. I didn't thought about the balance pool since I was able to execute normal tx (but those are like a 1/10th of what a safe creation cost, so maybe there was just enough for regular tx's 🤷 )

I tried The safe update and I still see the warning that the tx might fail, but I just bumped the gas up in the adv parameters and the warning is gone, so is not a relayer thing.

**Comment by iamacook** [comment]
> I tried The safe update and I still see the warning that the tx might fail, but I just bumped the gas up in the adv parameters and the warning is gone, so is not a relayer thing.

We've noticed RPC issues again today. Taking that into consideration, are you ok if we merge this?

**Comment by francovenica** [comment]
Yes, merge it

**Pull request merged**
