### PR TITLE
Chore: tune the CLA action

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves
The CLA action doesn't seem to be able to post a comment in external contributors' PRs.
It says
```
Error occured when creating or editing the comments of the pull request: Resource not accessible by integration
```
Trying to figure out why.

### CODE REVIEW

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
recheckcla

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
recheck

**Review by usame-algan — APPROVED** [review]

**Pull request merged**
