### PR TITLE
Update safe-deployments to latest version to support Neon contracts

### PR DESCRIPTION
**Pull request by Sj-001**
## What it solves
Added latest version of safe-deployments, that contains Neon EVM Devnet safe-contract addresses.
Resolves #

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by Sj-001** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by iamacook — APPROVED** [review]

**Comment by Sj-001** [comment]
recheck

**Comment by katspaugh** [comment]
The Safe Core SDK also needs to be updated to the version that has the updated safe-deployments.

**Comment by Sj-001** [comment]
> The Safe Core SDK also needs to be updated to the version that has the updated safe-deployments.

I see, that is a collection of multiple codependent packages. Should I create a PR fro that too?

**Comment by katspaugh** [comment]
Exactly, and they did some restructuring there which we haven't migrated to yet. In that [monorepo](https://github.com/safe-global/safe-core-sdk), there were previously packages called safe-core-sdk and safe-core-sdk-utils which this repo depends on. It's now renamed to protocol-kit, I believe.
Maybe there's still a branch where these packages exist, @germartinez can tell you more.

**Comment by Sj-001** [comment]
> Exactly, and they did some restructuring there which we haven't migrated to yet. In that [monorepo](https://github.com/safe-global/safe-core-sdk), there were previously packages called safe-core-sdk and safe-core-sdk-utils which this repo depends on. It's now renamed to protocol-kit, I believe. Maybe there's still a branch where these packages exist, @germartinez can tell you more.

Hey @germartinez , Can you please help update the safe-core-sdk to the latest one?

**Comment by katspaugh** [comment]
Looks like @germartinez already updated safe-deployments in safe-core-sdk. So you just need to bump its version to 3.3.3 in this PR.

**Comment by germartinez** [comment]
Please check the release of the Safe Core SDK here: https://github.com/safe-global/safe-core-sdk/releases/tag/r27.1
Also available on npm

**Review by katspaugh — APPROVED** [review]
Thank you! 👍

**Pull request merged**
