### PR TITLE
feat: Add pending analytics for Safe Apps

### PR DESCRIPTION
**Pull request by yagopv**
## What it solves
Add pending analytics for Safe apps

## How this PR fixes it
This PR adds:
- Pending common analytics
- SDK Analytics

## How to test it
This PR should add analytics for:

- [ ] Open Safe App
- [ ] Pin Safe App
- [ ] Unpin Safe App
- [ ] Search for Safe App
- [ ] Add custom Safe App
- [ ] Transaction Confirmed
- [ ] Transaction Rejected
- [ ] Shared App landing page visited
- [ ] Shared App chainId
- [ ] Open demo safe from shared app
- [ ] Open shared app after Safe creation
- [ ] Safe App method calls using the SDK

### CODE REVIEW

**Comment by yagopv** [comment]
@JagoFigueroa when testing this you can follow the checklist in the description

**Comment by mikhailxyz** [comment]
why are so many commits in here? 🤔

**Review by mikhailxyz — APPROVED** [review]

**Comment by yagopv** [comment]
> why are so many commits in here? 🤔

Because i started this from another one not merged in main

**Comment by JagoFigueroa** [comment]
I was testing this ticket while on dev test and all bueno from my side.

I am missing this case:  **Open shared app after Safe creation** because of this [ticket](https://github.com/safe-global/web-core/issues/696) but should be all good to be rechecked once it is implemented.

Gracias!

**Pull request merged**
