### PR TITLE
fix: validate dates

### LINKED ISSUE #476: Filter - Validate that "To" is always higher than "From"
## Bug description
This is a validation that was already done in safe-react. The "From" value should always be lower than the "To" value

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to any safe, transaction history
 2. Input in "From" any date
 3. Input in the "To" a date lower than From

## Expected result
The inputs "To" and "From" should highlight that the dates are wrong (from should be lower than to). The Apply button should be grayed out until those dates are fixed

## Obtained result
You can filter normally

## Screenshots
image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #476

## How this PR fixes it

"From" and "To" dates now validate against each other and are validation dependent on each other.

## How to test it

Enter conflicting dates above/below the other accordingly and observe the validation error.

## Screenshots
image

### CODE REVIEW

**Review by katspaugh — COMMENTED** [review]
They can also be the same date tho, can't they?

**Comment by iamacook** [comment]
> They can also be the same date tho, can't they?

Yes, and that passes validation:

image

**Review by katspaugh — APPROVED** [review]
It would be interesting to find out if the validation function can get away with using `getValues` instead of `watch`.
Looks good regardless!

**Comment by iamacook** [comment]
> It would be interesting to find out if the validation function can get away with using `getValues` instead of `watch`. Looks good regardless!

Good point. It does work with `getValues` and have changed it accordingly.

**Pull request merged**
