### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* [Epic] Safe Creation (#988) (A/B test)
* feat: Collapsable sidebar in Safe App view (#1169)
* feat(safe-apps): Add support for receiving analytics from our Safe Apps (#1066)
* add: data management tab with import all data button (#1103)

## Improvements
* feat: redesign address book import (#1137)
* refactor: simplify GTM logic + unmount on permission removal (#1047)
* Refactor: paginated NFT select (#1235)

## Bug fixes
* fix: Dislay an error when trying to transfer safe token (#1250)
* fix: Send current step with tracking event (#1249)
* Fix: show upgrade notification only to owners (#1070)
* fix(safe-apps): Safe apps analysis improvements (#1136)
* Fix: sandbox safe app icons (#1193)
* fix: show warning based on `trusted` flag (#1226)
* fix: flag Keystone wallets as hardware wallets + adjust modal `z-index` (#1194)
* fix: redirect to `/home` of Safe present in URL (#1183)
* Fix: added safes across chains (#1167)
* Fix: backdrop color (#1186)
* fix: handle invalid shortname in url (#1160)
* Fix: MUI Switch default color (#1189)
* fix: pressing enter doesn't set max (#1168)
* fix: checksum lowercase addresses + validate checksums (#1127)

## Docs & chores
* Chore: PR deployment action (#1197)
* add: docs for import all feature (#1152)
* fix: improve reliability of E2E tests (#1182)
* improve reliability of create_tx cypress test (#1196)

### CODE REVIEW

**Comment by katspaugh** [comment]
CloudFlare link: https://release-1-1-0.web-core.pages.dev/

**Comment by JagoFigueroa** [comment]
Hola team! I am having some trouble to see the analytic events for safe apps. No events are triggering for me on the apps available on the [safe apps RC](https://github.com/safe-global/safe-react-apps/pull/584). A couple of examples:

Tx-builder:

https://user-images.githubusercontent.com/92332710/204288218-ff229d1f-9d01-41be-9355-7b2ab97b8145.mp4

WC:

https://user-images.githubusercontent.com/92332710/204287538-897b7545-f638-416c-a04c-265453166df2.mp4

Any idea what the issue might be?

Un abrazo

**Comment by katspaugh** [comment]
I've just tried on https://release-1-1-0.web-core.pages.dev/gor:0xc8b4dA63f0b4413E4C8815143d28a642F6BD2309/apps?appUrl=https%3A%2F%2Fpr584--safereactapps.review-react-hr.5afe.dev%2Ftx-builder%2F and it does send out GTM events:

Screenshot 2022-11-28 at 15 05 53

Stupid question, did you accept all the cookies, @JagoFigueroa?

**Comment by JagoFigueroa** [comment]
You are right señor @katspaugh , I can see events as well. Was trying to trigger the newly implemented ones on our RC specifically to start with and as I could not see them thought it was a global issue 🤦  

I will move this conversation to safe-apps as well to see if there might be something off with those new events in particular. Gracias!

**Review by usame-algan — APPROVED** [review]
LGTM

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
Question:
I'm checking the safe apps GA events in the console and it seems that the same event is called several times (it depends on the app). They all seem to be the same event, just triggered several times. Is this correct?
Tagging @yagopv since you worked on that ticket
image
image

**Comment by yagopv** [comment]
It’s fine @francovenica we are quantifying the method calls, in this case the RPC method `eth_call` but not the parameters used to call the [method](https://www.quicknode.com/docs/ethereum/eth_call) itself that will be the ones varying between calls.

This analytic is being sent each time the Safe Apps uses SDK for a method call so even if the app is doing some wrong things in any case is the code in `web-core` the cause.

**Comment by francovenica** [comment]
@JagoFigueroa @liliya-soroka can you check the #1136 and #1194 ?

**Comment by francovenica** [comment]
I've checked the rest of the tickets on the list and they are fine. Just reported an issue with Safe update notifications 

Tomorrow I'll finish the regression checklist (signing with different wallets in different networs, AB, Spending limits, Tx lists, filters, send funds, etc...)

**Comment by JagoFigueroa** [comment]
Anotha one! (Not 100% sure if it is an issue for this one, please correct me if it is an expected change)

Wallet connection modal on prod
Screenshot 2022-11-29 at 10 02 12

Wallet connection modal on the RC

Screenshot 2022-11-29 at 10 02 02

**Comment by JagoFigueroa** [comment]
Sorry for the spam :pepe-scream:

There is a small issue (maybe inherited from the full screen mode for safe-apps?) on which now, the tx queue is shown in front of the transaction modal, making interaction a little bit tricky:

https://user-images.githubusercontent.com/92332710/204492733-2ccfea3b-a21e-4fe7-894c-827b85d54f9b.mp4

RC vs Prod:

Screenshot 2022-11-29 at 10 29 37

**Comment by katspaugh** [comment]
Regarding the wallet connection modal – I've noticed this too, probably an unintended change but it looks better IMHO. So I would keep it. @liliiaorlenko wdyt?

The new backdrop background color is correct.
---
@DaniSomoza could you take the Tx Queue overlap issue?

**Comment by francovenica** [comment]
I didn't found other issues than the ones reported in the comments of this ticket. once those are fixed we can deploy

**Pull request merged**
