### PR TITLE
fix: signing issues

### LINKED ISSUE #1113: Signing a message produces a hash different from the old interface
## Bug description
Snapshot and otterspace teams reported that signing messages doesn’t work in the new interface. For some reason, it produces a hash different from the old interface. for snapshot it fails constantly, but for otterspace it’s random. If you need more info/input from developers, there's `#safe-snapshot` channel in discord and a telegram group with otterscan. lmk if you need an invite

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Try to vote on a proposal with snapshot
 ----------
Or check the reproduction example in the repo here:
https://github.com/otterspace-xyz/gnosis-safe-error-example

## Expected result
Hashes match the old interface

## Obtained result
Hashes are different

### PR DESCRIPTION
**Pull request by dasanra**
## What it solves

Resolves #1113 

## How this PR fixes it
Ethers hashMessage requires that the message is decoded if it was utf8 encoded

## How to test it
Sign a snapshot testing proposal and see that the vote correctly reflects there
https://snapshot.org/#/fabien.eth/proposal/0xbe992f0a433d2dbe2e0cee579e5e1bdb625cdcb3a14357ea990c6cdc3e129991

### CODE REVIEW

**Review by mikhailxyz — APPROVED** [review]

**Review by katspaugh — APPROVED** [review]
🚀

**Comment by rmeissner** [comment]
would be nice to add some tests for the `getDecodedMessage` method.

**Comment by JagoFigueroa** [comment]
Tested and merged in: https://github.com/safe-global/web-core/pull/1120 😉

**Comment by dasanra** [comment]
Changes were cherry-picked for the hotfix at #1120 

Mergeback to `dev` was done at https://github.com/safe-global/web-core/pull/1129

**Pull request closed without merging**
