### PR TITLE
Chore: add a CLA checking action

### LINKED ISSUE #1257: Add a CLA signature check
Contributors must sign a CLA before merging.

[Docs.](https://www.notion.so/gnosis-safe/Migrate-Contributor-License-agreement-CLA-7cd2da532f5143238c8e2a0348e07c96)

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #1257

## How this PR fixes it

Copies the action from safe-react. The only difference is it's now linking directly to the website instead of an .md file in the repo.

### CODE REVIEW

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
recheckcla

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
recheckcla

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by katspaugh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by iamacook — APPROVED** [review]

**Pull request merged**
