### PR TITLE
[Epic] Governance visibility

### LINKED ISSUE #969: [Epic] Governance Visibility
## Overview

Create better visibility for SafeDAO governance within our web interface

### Create a Governance section in the Dashboard

- [x] #974
- [x] #970
- [x] #976

### Exploratory work:
- [x] #1221
- [x] https://github.com/safe-global/web-core/issues/1222

### Fixes:
- [x] https://github.com/safe-global/safe-react-apps/issues/590
- [x] https://github.com/safe-global/safe-react-apps/issues/591
- [x] https://github.com/safe-global/web-core/issues/1275
- [x] https://github.com/safe-global/web-core/issues/1269
- [ ] make sure that text all over the widget has the font and size according to the design

## Links

Problem Statement: https://www.notion.so/gnosis-safe/Safe-governance-has-no-visibility-in-our-product-interfaces-9ac542d352e0405486dc6380d4b7198b
Ideation: https://www.notion.so/gnosis-safe/Safe-governance-visibility-8ba5f8f4d58249c1bdac6c3ae2429992
Figma: https://www.figma.com/file/8nKOe7h90OS7jmn3nksbq9/Governance-visibility-widgets?node-id=1%3A2&t=6xgktRKjZ8vRyHbW-0

## Test cases 
https://www.notion.so/gnosis-safe/7a60bea771e8408aa641a86f0c6f163c?v=c0914058adc14f54954da24e75d0ac62

### Screenshots (1024px)
Screenshot 2022-11-17 at 10 47 36
Screenshot 2022-11-17 at 10 48 05
Screenshot 2022-11-17 at 10 49 18

### PR DESCRIPTION
**Pull request by DiogoSoaress**
## What it solves

Resolves #969

## How this PR fixes it

- #974
- #970
- #976
- #1221
- https://github.com/safe-global/web-core/issues/1222

## How to test it
Testing steps can be found in the individual tickets.

## Analytics changes
N/A

## Screenshots
Screenshot 2022-11-28 at 09 19 56
Screenshot 2022-11-28 at 09 20 20

### CODE REVIEW

**Comment by liliya-soroka** [comment]
approved. Only the loading widget state is under question , but it's not critical for the feature

**Comment by yagopv** [comment]
Seems to be working fine @katspaugh, did some txs with Uni and Cow apps and checked returned data from the  SDK with the test app. The code is fine for me, same we talked in the prev pr that was merged here.

`useChainInfo` is a refactor for removing code from `AppFrame` or is fixing something?

**Review by yagopv — APPROVED** [review]

**Comment by katspaugh** [comment]
@yagopv thanks! `useGetSafeInfo` you mean? It was requested by Aaron that I extract it so as to not repeat the same logic.

**Comment by yagopv** [comment]
Oook!! Nice

**Pull request merged**
