### PR TITLE
Fix: show upgrade notification only to owners

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves
The upgrade notification is only actionable if you're the owner.
Noticed this when opening the demo safe.

## How to test
1)
* Open a 1.1.1 Safe that doesn't belong to you (or simply disconnect the wallet)
* The upgrade notification should NOT pop up

2)
* Open a 1.1.1 Safe as an owner
* Observe the notification

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
I cannot see the notification even with the owner of the safe, but also I cannot see the "update" button at all, so maybe that's why the notification is not popping up.

image

**Comment by katspaugh** [comment]
@francovenica it's not ready for QA.

**Comment by francovenica** [comment]
I'm still having the same issue as before: no notification and the update button is not there
image

**Comment by katspaugh** [comment]
@francovenica you're probably using the staging CGW. It sadly doesn't detect outdated Safe versions.

cc @safe-global/safe-services

**Comment by fmrsabino** [comment]
> @francovenica you're probably using the staging CGW. It sadly doesn't detect outdated Safe versions.
> 
> cc @safe-global/safe-services

I suspect this is more of a data related issue that should be checked. The production deployment is the same as the staging one (minus some minor commits going into the next release).

So it should detect outdated safes in the same way as the production one. The data used by these checks might be the differing factor.

@francovenica can you share the Safe Address, chain and environment being used? Thanks!

**Comment by fmrsabino** [comment]
> @fmrsabino here's an example:
> 
> * Prod, shows OUTDATED correctly: https://safe-client.safe.global/v1/chains/1/safes/0x85C9f5aA0F82A531087a356a55623Cf05E7Bb895
> * Staging: UP_TO_DATE https://safe-client.staging.5afe.dev/v1/chains/1/safes/0x85C9f5aA0F82A531087a356a55623Cf05E7Bb895

The `recommendedMasterCopyVersion` on Staging is `1.1.1`: https://safe-config.staging.5afe.dev/api/v1/chains/1/

Last time it was changed was on Aug. 3, 2021. I can set this value to be the same as production but maybe it was set to this value for testing purposes.

**Comment by katspaugh** [comment]
Oh I see, yes, pelase @fmrsabino!

**Comment by fmrsabino** [comment]
> Oh I see, yes, please @fmrsabino!

Updated ✅ https://safe-config.safe.global/api/v1/chains/1/

**Comment by katspaugh** [comment]
Thanks Fred! It shows OUTDATED correctly now 👍 

@francovenica please give it another go.

**Comment by francovenica** [comment]
Now it works fine.
The notification is only shown to a connected user who is also owner of that safe.

The Update button is there again as well
Tested with the CGW switch on and off and it works fine for both.

**Pull request merged**
