### PR TITLE
Chore: add ts-prune

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves
Adds ts-prune to find unused code. Plus a command that runs lint, prune and prettier:

```
yarn fix
```

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]
Nice addition. There are quite a few exports that aren't needed 👍

**Comment by katspaugh** [comment]
If there are, it didn't find any. 🤔 

It does delete the ones I add to test it tho.

**Comment by usame-algan** [comment]
> If there are, it didn't find any. 🤔

I ran `ts-prune` on its own maybe thats why 🤔 
But for example `TokenTransferSteps` is exported even though its only being used in the same component

**Comment by katspaugh** [comment]
Ah, I see. When I run it separately, it lists the unused exports but doesn't delete them. It does delete unused imports tho.

**Pull request merged**
