### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* feat: default token list toggle (filter out spam tokens) (#1549)
* Feat: NFT preview (#1668)

## Refactoring
* Refactor: move safe address from path to query (#1622)

## Bug fixes & improvements
* Fix: lazy load app icon iframes (#1690)
* feat: add tracking to default token list menu (#1678)
* chore: update vulnerable dependency (#1684)
* Add Arbitrum Nova and Arbitrum Goerli (#1682)
* Fix: sort apps alphabetically (#1672)
* Fix: remove claiming app from dashboard (#1680)
* fix: spending limit validation (#1681)
* Fix: Safe Apps loading state (#1674)
* fix blur nft links (#1675)
* Optimize nfts skeletons
* fix: change Safe Apps text (#1673)
* Fix: skeleton loaders
* fix: Sticky z-index in assets and NFTs (#1670)
* Docs: add a comment on wallet events (#1686)
* fix: mock fetch implementation (#1685)
* Fix: avoid multiple pending txs with the same nonce (#1696)

### CODE REVIEW

**Comment by liliya-soroka** [comment]
1. 
image

**Comment by francovenica** [comment]
In this RC the NFT are not showing its icon. I've checked in the previous RC (1.5.0) and it shows there so they should show in this RC too: 
(Prod CGW is enabled in both)

https://release_1_6_0--webcore.review-web-core.5afe.dev/balances/nfts?safe=eth:0x8675B754342754A30A2AeF474D114d8460bca19b

image
image

**Comment by katspaugh** [comment]
That's expected as per design.

**Comment by francovenica** [comment]
Question, didn't we add in previous releases a change that would make the "you have to upgrade your safe" notification not popUp every time you connect your wallet? or we never merged it?. Currently the notification pops up everytime you connect

**Comment by francovenica** [comment]
The list of this ticket has been verified and is fine. rechecked the repeated nonce again and it works fine (even if you are fast enough, the 2nd tx with the same nonce is cancelled right away never gets to the queue list).
Lili checked most of the regression and I rechecked it and checked the spending limit funtionality

Note: @JagoFigueroa was going to check apps a bit, but I didn't have a chance to talk to him if everything is fine. If it is, then the RC is good to go

**Comment by katspaugh** [comment]
Awesome, thanks @francovenica!

> Currently the notification pops up everytime you connect

You're referring to #1530, which is still open. We only added some additional info on the settings page.

**Review by liliya-soroka — APPROVED** [review]
approved

**Pull request merged**
