### PR TITLE
fix: filter injected wallets per chain

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Reimplementation of #703

## How this PR fixes it

Injected wallets are now adjusted according to whether they are present in the `disabledWallets` array.

All wallets are initially loaded and then [onboard's `setWalletModules` is called](https://github.com/safe-global/web-core/blob/main/src/hooks/wallets/useOnboard.ts#L131-L132) with the [supported wallets](https://github.com/safe-global/web-core/blob/main/src/hooks/wallets/wallets.ts#L81-L88). The `ChainInfo` is now passed to wallet modules to allow for [filtering](https://docs.blocknative.com/onboard/injected-wallets#excluding-wallets).

## How to test it

Open the Safe and view the available wallets. Disable an inject wallet (tally, frame, opera, trust or metamask) via the CGW and refresh the page. Observe the disabled wallet is no longer available.

### CODE REVIEW

**Comment by iamacook** [comment]
I'm aware of the failing tests.

**Review by katspaugh — APPROVED** [review]
LGTM.
FYI, I also modified the jest setup in a similar way in my PR.

**Comment by katspaugh** [comment]
It looks like in the config-service admin, you need to explicitly enable each wallet. It means, we lose a lot of flexibility with the "detected wallet" module being filtered based on an allow-list. I suggest we keep it open-ended for now, and think about this if we encounter a problem with some of the injected wallets.

**Comment by iamacook** [comment]
> I suggest we keep it open-ended for now, and think about this if we encounter a problem with some of the injected wallets.

I'll close this for now then. We can use it as reference when we eventually tackle this in the future.

**Pull request closed without merging**
