### PR TITLE
Release/1.7.0

### PR DESCRIPTION
**Pull request by iamacook**
## Features
* [Epic] EIP-1271 support (#1162)
* Feat: add OpenSea links for l2 chains (#1720)

## Bug fixes & improvements
* fix: show new name in review modal (#1721)
* Fix: apps sdk widget design (#1716)
* fix: filter governance app tag (#1727)
* test: add pending actions E2E (#1688)
* Add decimal validation to spending limit form (#1718)
* Display manual gasLimit in GasParams overview (#1711)
* Fix: single transaction skeleton (#1709)
* fix: alphabetically sort remote apps (#1719)
* Fix: pre-render the nav sidebar (#1715)
* Docs: add a checklist to the PR template (#1717)
* Chore: remove an unnecessary deployment step (#1710)
* Chore: update MUI (#1702)
* fix: migrate widgets to the governance app (#1640)
* [Fix][Mobile] Hamburger menu not working on welcome page (#1698)
* #1747 
* https://github.com/safe-global/web-core/pull/1753
* https://github.com/safe-global/web-core/pull/1755
* .well-known/apple-app-site-association

### CODE REVIEW

**Comment by liliya-soroka** [comment]
1. Governance widget on prod Ethereum: Loading section... instead of the widget 
image

**Comment by liliya-soroka** [comment]
2. Nothing happens after the badge is clicked in the header 
image

**Comment by liliya-soroka** [comment]
@iamacook , nothing happens when Claiming or redelegate are clicked in the governance app when the staging env was used 
image

**Comment by francovenica** [comment]
Note: The button in the app takes to the safe-core.stg enviroment even when I'm in the RC. I'll assume this is correct since we are using stg services, but I'll wanted to keep it here as a sidenote
image

**Comment by francovenica** [comment]
I was able to test EIP1271 only with the Stg CGW enabled since it only works there. The problem is that stg services are not working well, txs get stuck in the "indexing" status forever, so I wasn't able to test the on-chain tx for this feature.

**Comment by francovenica** [comment]
SafeTxGas is shown in safes 1.3.0, even tho it can't be changed. Is not that way in prod currently and I don't remember a ticket changing this. 
This is a regular send funds tx to be executed:
image

**Comment by francovenica** [comment]
The "Execute now" checkbox is also missing for safes 1/x. I remember we talked about removing the option because of issues, but I want to know which ticket removed that and if it is on the list of this RC
image

**Comment by francovenica** [comment]
In the queue tab, the skeleton is pushing the tx that are already loaded. I think if the tx were already loaded by visiting the queue tab the skeleton should not appear at all
This shows for a split second, but it doesn't look good
image

**Comment by iamacook** [comment]
> The button in the app takes to the safe-core.stg enviroment even when I'm in the RC. I'll assume this is correct since we are using stg services, but I'll wanted to keep it here as a sidenote

This is as intended. The link is relative to the envrionment.

> I was able to test EIP1271 only with the Stg CGW enabled since it only works there. The problem is that stg services are not working well, txs get stuck in the "indexing" status forever, so I wasn't able to test the on-chain tx for this feature.

It was enabled on production at the beginning of this week. Does it not work for you? Regarding staging services, there were indexing issues on Goerli yesterday. I'd suggest testing that again.

> SafeTxGas is shown in safes 1.3.0, even tho it can't be changed. Is not that way in prod currently and I don't remember a ticket changing this.

This was changed [here](https://github.com/safe-global/web-core/pull/1711) by accident. I have fixed it [here](https://github.com/safe-global/web-core/pull/1753).

> The "Execute now" checkbox is also missing for safes 1/x. The checkbox is in production currently, so I assume it was changed here.

It's showing in the UI for me and I just checked the code and see no recent changes. Can you test it again?

> In the queue tab, the skeleton is pushing the tx that are already loaded. I think if the tx were already loaded by visiting the queue tab the skeleton should not appear at all
> This shows for a split second, but it doesn't look good

I cannot replicate this either. Can you try again?

**Comment by francovenica** [comment]
> It was enabled on production at the beginning of this week. Does it not work for you? Regarding staging services, there were indexing issues on Goerli yesterday. I'd suggest testing that again.

With the prod CGW enabled the "message" tab doesn't show 
messages

**Comment by iamacook** [comment]
> > It was enabled on production at the beginning of this week. Does it not work for you? Regarding staging services, there were indexing issues on Goerli yesterday. I'd suggest testing that again.
> 
> With the prod CGW enabled the "message" tab doesn't show

Apologies, I forgot that it is currently config depenedant. We would have to set it as an enabled features on production. I do not have access to do so though.

**Comment by francovenica** [comment]
The skeleton issue is still visible for me. Have 1 tx waiting in queue and switch back and forth between history and queue tabs:
skeleton

**Comment by francovenica** [comment]
I've checked the skeleton is gone and the "execute now" checkbox is again present. the fix is good

**Comment by francovenica** [comment]
The RC looks good to go

Remember that the governance app desn't work here when the Prod CGW is enabled, idk if there is something else to do before deplyoing it.

**Comment by francovenica** [comment]
The governance app was fixed to work with the Prod CGW in goerli. The widget works and I try redelegating in a safe I have, so the app works as well
image

**Review by usame-algan — APPROVED** [review]
LGTM

**Pull request merged**
