### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* [Epic] Transaction replacement (#1079)
* [Epic] Governance visibility (#1256)
* feat(safe-apps): Add custom Safe App warning  (#1258)
* Added sandbox attribute to Safe App iframe (#1252)

## Bug fixes
* fix: Change status colors in safe creation (#1339)
* fix: allow resetting to recommended nonce of 0 (#1329)
* fix: alter threshold change warning text (#1332)
* fix: Track safe cretion events under the same category (#1312)
* fix: Reset Core SDK when switching safes (#1259)
* Fix format amount review modal (#1265)
* Fix: div inside p (#1322)
* fix: get fallback handler from SDK (#1282)
* fix: redesign (external) links (#1241)
* refactor: use `isValidTransaction` from SDK (#1285)
* fix: Revert accordion transitions (#1304)
* fix: fallback to "Contract interaction" for module (#1301)
* fix: prevent scroll adjusting number inputs (#1280)
* fix: vertical scrolling after opening the Mobile paring modal (#1295)
* fix: Handle timeout error in safe creation (#1293)
* Fix: link to old app from the import page (#1306)
* fix: Account switching with mobile pairing and WC (#1278)
* add safe token address to goerli (#1274)
* fix(safe-apps): Rename transaction confirmed event to propose transaction (#1263)
* Import Safe Core SDK from @safe-global (#1266)
* #1342 
* #1340 
* #1363 
* #1360 
* #1368 

## Chores
* Chore: migrate gateway sdk package to safe-global (#1333)
* Chore: add a CLA checking action (#1292)
* Chore: a new domain for PR deployment (#1271)
* Chore: use branch name for PR deployments + prettify the comment (#1288)

### CODE REVIEW

**Comment by katspaugh** [comment]
As @schmanu mentioned, we need to release the [Claiming App](https://github.com/safe-global/safe-react-apps/tree/development/apps/safe-claiming-app) before we release this.

**Comment by liliya-soroka** [comment]
1. @schmanu , claiming app instead of Governance widget 
image

**Comment by liliya-soroka** [comment]
1. Text is displayed inside amount field
-Go to the send funds
- enter 1. to the amount field
image

**Comment by liliya-soroka** [comment]
2. module tx is not fixed fully - fix: fallback to "Contract interaction" for module (https://github.com/safe-global/web-core/pull/1301)
Settings icon is used instead of contract interaction 
image

**Comment by JagoFigueroa** [comment]
Hola team! For this [ticket](https://github.com/safe-global/web-core/pull/1293) regarding timeouts on safe creation the expected result is shown to me after 6,5 minutes on the case that I reload the page:

Screenshot 2022-12-12 at 17 17 55


but unfortunately on the case that I don't perform a manual page reload it will be stuck on this screen forever (I have waited for 20 minutes in chrome)

Screenshot 2022-12-12 at 17 05 01

**Comment by JagoFigueroa** [comment]
Hola again! For this señor [ticket](https://github.com/safe-global/web-core/pull/1306) regarding the export/import for this case mentioned on the ticket:

- Show the "Overwrite data?" alert only after dropping a file

I can see that we are showing the alert before uploading the JSON file. Nothing major or anything but Is it expected?

Screenshot 2022-12-13 at 09 59 35

Cheers!

**Comment by JagoFigueroa** [comment]
Regarding transaction replacement modal, presentation is a bit off when viewing it from a mobile device (video is from the browser but in mobile resolution  I was able to reproduce this as well on my Iphone 13 pro):


https://user-images.githubusercontent.com/92332710/207279666-f907907e-9dc3-4a65-a6a9-10ed79073684.mp4

**Comment by liliya-soroka** [comment]
Thank you for the fixes. The 1.2.0 rc is approved to go live :token-symbol-safe:

**Review by usame-algan — APPROVED** [review]

**Review by iamacook — APPROVED** [review]

**Pull request merged**
