### PR TITLE
fixes #1524

### LINKED ISSUE #1524: [Tx details] the icon in UI is misplaced
## Bug description

Screenshot 2023-01-11 at 13 53 50

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Transactions
 2. Expand the details of some tx

## Expected result
The icon should be centered.

### PR DESCRIPTION
**Pull request by abheektripathy**
## What it solves
Resolves #1524 

## How this PR fixes it
Passed `TransferActions` as children to `EthHashInfo` , the icon is now centered.

## Screenshots
image

### CODE REVIEW

**Comment by abheektripathy** [comment]
recheck

**Comment by abheektripathy** [comment]
recheck

**Comment by abheektripathy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by abheektripathy** [comment]
recheck

**Review by katspaugh — APPROVED** [review]
Nice, great work!

**Pull request merged**
