### PR TITLE
Release 1.8.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* [EPIC] Relaying (#1776)
* feat: show alert for new versions in settings (#1810)
* feat: display Fallback Handler address (#1785)
* feat: buttons to expand/collapse all actions (#1789)
* Feat: better UX for disabled tx buttons (#1712)
  * refactor: delay switching networks until execution (#1746)
* feat: allow initialisation of SDK with unsupported mastercopies (#1738)
* feat: add relay debug toggle #1847 

## Bug fixes
* fix: add help centre article (#1850)
* Fix: remove atomic0 links and add Zerion links on the NFTs page (#1846)
* fix: height of "Explore Safe Apps" card (#1835)
* fix: Dismiss update safe notification for 90 days (#1812)
* fix: Add licenses page (#1819)
* fix: add secrets to build workflow (#1834)
* fix: rejection transaction description + link text (#1821)
* fix: Token list layout on mobile screens (#1806)
* Fix: update safe-react-components (#1805)
* fix: DateTime jest test (#1804)
* fix: support tokens with no decimals (#1794)
* Fix: sort Safe App tags (#1793)
* Fix: strip query params from Sentry events (#1784)
* Fix: rm automatic safe-react data migration (#1778)
* Fix: tx-summary word-break only on mobile (#1772)
* fix: Stay on the same route when switching safes (#1756)
* fix: add link to messages placeholder (#1771)
* fix: Only store owned safes for their given chainId (#1760)

## Improvements
* Refactor: minimize the usage of the static chains config (#1692)
* refactor: simplify `isValidMasterCopy` (#1773)
* chore(deps-dev): bump @openzeppelin/contracts from 4.8.1 to 4.8.2 (#1736)
* chore(deps): bump json5 from 1.0.1 to 1.0.2 (#1768)
* Chore: replace deprecated set-output in the deploy workflow (#1769)
* test: e2e manually hide tokens (#1757)
* chore: remove EIP-1271 docs (#1761)
* chore: fix typo (#1779)

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Review by usame-algan — APPROVED** [review]

**Comment by francovenica** [comment]
This is an old issue where the GNO chain would have trouble to properly estimate the gas needed to execute the tx. This was usually solved by just bumping up the gas limit in tx, but with the relayer we cannot do that
image

The tx fails (or takes a while)
image

**Comment by schmanu** [comment]
@francovenica 
It is possible to increase the gas limit when relaying if you click on the "Estimated fee" Accordion.

The next release will add a small Icon to those quite hidden Accordions.

Screenshot 2023-04-05 at 08 48 05

**Comment by katspaugh** [comment]
Added a fix for the NFT page links.

**Comment by francovenica** [comment]
The RC looks good

I've checked the tickets that are funtionally testeable
The relayer works fine in GNO, for safe creation and tx execution
Tested tx without the relayer and those work fine too
The rest looks good as well: Safe creation/loading, Aadress book, spending limit, owner edition, tested a few apps, Tx queue and history, connections and tx with different walletes...

I'd like before passing this to see if we can fix https://github.com/safe-global/web-core/issues/1853 and merge it here before the release

**Comment by iamacook** [comment]
> I'd like before passing this to see if we can fix #1853 and merge it here before the release

@francovenica, this is [an issue with MM](https://github.com/MetaMask/metamask-extension/issues/18453) itself (@schmanu has been able to replicate it on prod). They intend to fix this on their end [in ~2 days](https://github.com/MetaMask/metamask-extension/issues/18453#issuecomment-1502435232).

**Comment by francovenica** [comment]
Ok, Thanks for digging on it @schmanu . Good that is not something we have to fix, bummer that we depend on others to fix it

**Pull request merged**
