### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by katspaugh**
## Features
* Feat: support 1.0.0 Safes (#1588)

## Improvements
* Switch app network to wallet network on /welcome (#1587)
* "Recipient" -> "Recipient address or ENS" (#1570)
* Explorer link in multisend/spending limit tx notifications (#1542)
* feat(safe-apps): Use SignMessageLib from safe-core-sdk (#1419)

## Major fixes
* Fix: propose immediately executed txs (#1569)
* fix: iterate signing method on error (#1589)
* Add increment for failing estimations in Gnosis Chain (#1559)
* fix: GA tracking wrong eventLabels, missing event type, overtracking wallet connect event (#1547)

## Minor fixes
* fix: asset selection validation (#1583)
* fix: Handle safe creation errors (#1591)
* fix: reset error boundary after navigation (#1586)
* fix: `EthHashInfo` nesting (#1590)
* fix: `merge` hydration of persisted state (#1552)
* fix: transaction info styling (#1576)
* fix: DOM nesting error (#1585)
* fix: Reduce cummulative layout shift (CLS) (#1577)
* fix: ref forwarding (#1578)
* fix: align the ...-menu with EthHashInfo
* fix: position executor in transaction stepper (#1574)
* fix: prevent scrollbars on Safe App icons (#1565)
* fix: Remove last used wallet when disconnecting (#1571)
* refactor: replace Stepper for MUI's List (#1467)
* style: mobile Address Book layout (#1503)
* fix: wait until successful SDK call to set pending state (#1529)
* fix: show input loading state when "Add Safe" from the sidebar (#1528)
* render an img tag in SafeAppIcon iframe (#1516)

## Tests
* Extend create safe e2e test (#1543)
* add smoke test for spending limit modal (#1581)

### CODE REVIEW

**Comment by francovenica** [comment]
I've swapped an owner in this safe about 15 mins ago. It took a manual reload to see the tx in the history tab (Safe 1/x, with signing and execution at the same time) and the old owner is still listed in the settings 
https://dev--webcore.review-web-core.5afe.dev/gor:0x41EfabA9C6264BA81f235B7Bc2e3eb2390782790/settings/setup
owner swap

**Comment by katspaugh** [comment]
Looks like a backend hiccup. By the time it lands in the history it should already drop the untrusted flag (because it wasn't signed originally). Give it some time.

**Comment by francovenica** [comment]
Ok, yes, it fixed it on its own. after a while

**Comment by francovenica** [comment]
I don't see this ticket working: https://github.com/safe-global/web-core/pull/1542 (the link to the block explorer in the notification after executing a tx), but also I see that the ticket was created because of the removal of the proposal of tx that are created and executed at the same time, thing that we reverted. So... maybe is ok for this ticket not to be working?

**Comment by francovenica** [comment]
Ticket 1547.
I'm getting some inconsistent calls respect on how it was working on that original ticket. Before reporting it as an issue I'll debug it with Usame directly

**Comment by francovenica** [comment]
I'm not sure how to validate https://github.com/safe-global/web-core/pull/1559. I'll request help from Dani Sanchez when possible

**Comment by katspaugh** [comment]
The block explorer link will now appear only for transactions that will never appear in the queue (e.g. spending limit txs). Regular immediate executions are now proposed like before.

Regarding the Gnosis Chain gas, you need to set a custom safeTxGas (from a Safe App), and compare the resulting gas with production. It should be +30% on this branch.

**Comment by katspaugh** [comment]
Here's a new one: https://github.com/safe-global/web-core/pull/1599

**Pull request closed without merging**
