### PR TITLE
add: social sharing meta tags

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
Adds social sharing meta tags to display a preview image and description when sending a link to a safe on messaging / facebook / twitter

## How to test it
Send a link to the deployed version on slack / twitter

## Analytics changes
None

### CODE REVIEW

**Review by katspaugh — COMMENTED** [review]
The code looks good, but does the image have to be a JPG?
PNG would look nicer.
And please run it through https://tinypng.com to reduce the size.

**Comment by schmanu** [comment]
> The code looks good, but does the image have to be a JPG? PNG would look nicer. And please run it through https://tinypng.com to reduce the size.

done!

**Review by katspaugh — APPROVED** [review]
Approved, let's merge it now, and check again once the new domain goes live.

**Comment by JagoFigueroa** [comment]
After talking with Manu the testing for this ticket will be done after it is deployed. Thanks!

**Pull request merged**
