### PR TITLE
security: add CSP headers

### PR DESCRIPTION
**Pull request by schmanu**
- add ContentSecurityPolicy

- add Strict-Transport-Security

### CODE REVIEW

**Comment by katspaugh** [comment]
Beamer isn't working now:
```
Refused to load the script 'https://app.getbeamer.com/js/beamer-embed.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com 'unsafe-eval'".
```

@schmanu could you please add GTM auth vars to the secrets on CloudFlare and check that GTM works?

**Comment by schmanu** [comment]
@katspaugh I will add `https://app.getbeamer.com/js/beamer-embed.js` to the `script-src` directive.

I checked gtm locally and it worked. I will double check and provide a screenshot.

**Comment by katspaugh** [comment]
@schmanu I wouldn't limit external hosts at this moment, because GTM loads analytics which uses a different host.

**Comment by schmanu** [comment]
@katspaugh 
I went through these docs by google for managing CSP directives with gtm and google analytics: https://developers.google.com/tag-platform/tag-manager/web/csp 

I added all exceptions they mentioned there in my latest commit. I tried it locally (with the prod gtm auth) and didnt see any errors on the console / network from beamer / gtm / analytics.

**Review by katspaugh — APPROVED** [review]
LGTM!

**Pull request merged**
