### PR TITLE
Release v1.3.0

### PR DESCRIPTION
**Pull request by katspaugh**
# Changelog for version 1.3.0

## Features
- Spam tokens: Manually hide tokens (#1377)
- Redesign welcome page (#1471)
- Redesign Load Safe (#1405)
- Allow switching the wallet (#1496)

## Bug fixes
- Use custom safeTxGas for simulations (#1439)
- Add PWA fields in the manifest (#1499)
- Trigger validation upon owner removal (#1477)
- Async validation loader in AddressInput (#1464)
- Don't show unread badge if showing all (#1488)
- Adjust error color (#1485)
- Keyboard support (#1454)
- Add global focus style override (#1451)
- Do not hardcode year in copyright (#1478)
- Don't show previous Safe notifications (#1473)
- Add owner icon to confirmations (#1436)
- Update signers confirmations (#1468)
- Use new app deployment url (#1472)
- Custom app warning flash (#1440)
- Add a chain switch button in Safe creation (#1502)

## Technical improvements
- Update @gnosis.pm/safe-deployments to v1.18.0 (#1507)
- Refactor: Remove old safe creation code (#1495)
- Refactor: rename ExternalLink prop (#1460)
- Chore: update all packages to the latest (#1470)
- Downgrade RHF version to 7.41.1 (#1494)
- Chore: roll back onboard-core (#1476)
- Create safe e2e test (#1500)
- a/b tested promotion of hiding spam tokens (#1504)

##Found issues 
- https://github.com/safe-global/web-core/issues/1513
- https://github.com/safe-global/web-core/issues/1519
- https://github.com/safe-global/web-core/issues/1520

### CODE REVIEW

**Review by iamacook — APPROVED** [review]

**Review by DiogoSoaress — APPROVED** [review]

**Review by schmanu — CHANGES_REQUESTED** [review]
Shortly blocked to include the PR which fixes the colors for the `OnboardingTooltip` button in dark mode.

**Review by schmanu — APPROVED** [review]
Fixed the button! Let's go 🚀

**Review by usame-algan — APPROVED** [review]
LGTM

**Comment by francovenica** [comment]
So far I've checked the list in the description and reported 2 issues, only one of them major. I Still have to finish the regular regression list (tx singing, owner edition, AB, etc...)

**Comment by katspaugh** [comment]
Thanks @francovenica! Please always add new issues to the project. And in case of release regressions – straight to ToDo.

**Comment by francovenica** [comment]
Looks good to me

The issues reported were fixed (the fix of the 1520 still has to be merged, but it was tested individually and it works fine)

Ended the regression and I didn't find issues
Safe creation and adding
Wallet connection
Tx creation and execution
Tx replacement
use of MM, WC, Trezor, Ledger, Mobile pairing
Tx status in queue and history tabs
Filter in history tab
Address book (import export, add/remove entries)
Settings > Owners > owner edition (add/remove/replace)
Settings > Policies
Settings > Spending limit (creation, removal edition)
Spending limit use (send funds)

**Pull request merged**
