### PR TITLE
fix: minor visual issues in the Safe Apps Landing page

### LINKED ISSUE #695: [Share app] Visual issues
## Description
A small list of issues affecting the share apps screen on web-core that I think it would be nice to fix for the release.

## Issues:
 1. Unnecessary spacing on the right for address selector (for both light and dark themes). 
share, visual, space on the right

 2. Light theme icons on dark theme: share, visual - dark theme icons

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves

Resolves #695 

## How this PR fixes it

- Added css classes to SVG icons
- Added `autoWidth` prop in the Safe Selector to automatically set the width of the popover according to the menu items

## Screenshots

Captura de pantalla 2022-10-04 a las 13 46 19

Captura de pantalla 2022-10-04 a las 14 29 17
Captura de pantalla 2022-10-04 a las 14 29 28

### CODE REVIEW

**Comment by katspaugh** [comment]
Screenshot 2022-10-06 at 08 43 13

☝️ something is wrong with the stroke thickness in this SVG.

Also, is it me or the lines look hairy in both icons? Some weird smoothing algo. The old icons were the same.

**Comment by DaniSomoza** [comment]
> Screenshot 2022-10-06 at 08 43 13
> 
> ☝️ something is wrong with the stroke thickness in this SVG.
> 
> Also, is it me or the lines look hairy in both icons? Some weird smoothing algo. The old icons looked smoother.

it seems that the SVG has some weird `<paths />` acting as stroke:

Captura de pantalla 2022-10-06 a las 13 20 30


I think that the best option here is just remove them:

Captura de pantalla 2022-10-06 a las 13 20 55
Captura de pantalla 2022-10-06 a las 13 21 10

What is your opinion about it?

**Review by katspaugh — APPROVED** [review]
Thanks Dani!

**Comment by JagoFigueroa** [comment]
I forgot to post a comment giving the ok :pepe-scream: todo bueno señores, thanks!

**Pull request merged**
