### PR TITLE
refactor: use `UrlObject`s for internal links

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Difficult to understand link structure

## How this PR fixes it

All internal links have been reformatted to `UrlObject`s.

## How to test it

The following links should work as before:

- Safe token widget
- Dashboard: assets, NFTs, pending and view all transactions
- Safe Apps: opening internal/external apps, sharing and demoing them
- Opening Safes via the sidebar
- Notifications: updating the Safe, transaction lifecycles and invalid mastercopy (which should open in a new tab).

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Nice!

**Comment by francovenica** [comment]
The safe token widget doesn't have a link at all
https://refactor-links.web-core.pages.dev/eth:0x8675B754342754A30A2AeF474D114d8460bca19b/home

image

**Comment by iamacook** [comment]
> The safe token widget is not clickable at all

I cannot replicate this. Please can you check again as it may have been related to the gateway migration.

**Comment by katspaugh** [comment]
Tested, works fine. Safe token widget works now. ✅

**Pull request merged**
